#pragma once

#include <window_settings.h>

const double UNIT_SHAPE_BOUNDS_COEFFICIENT = 0.8;
const double BULLET_SHAPE_BOUNDS_COEFFICIENT = 0.5;

const int VERTICAL_DOTS_AMOUNT = 8;
const int HORIZONTAL_DOTS_AMOUNT = 8;

const double VERITCAL_GAP_SIZE = WINDOW_HEIGHT / (double)VERTICAL_DOTS_AMOUNT;
const double HORIZONTAL_GAP_SIZE = WINDOW_WIDTH / (double)HORIZONTAL_DOTS_AMOUNT;

const int MIN_ENEMY_UNITS_AMOUNT = 5;
const int MAX_ENEMY_UNITS_AMOUNT = 10;
const double ENEMY_UNITS_SMALL_SPAWN_GAP = 1100;
const double ENEMY_UNITS_BIG_SPAWN_GAP = 3500;
const double TIMER_REDUCTION_AFTER_ENEMY_DEATH = 150;

const int WEAK_ENEMY_SPAWN_CHANSE = 48;
const int STRONG_ENEMY_SPAWN_CHANSE = 38;
const int MIGHTY_ENEMY_SPAWN_CHANSE = 100 - WEAK_ENEMY_SPAWN_CHANSE - STRONG_ENEMY_SPAWN_CHANSE;

const int ENEMY_WITH_SUPER_ATTACK_SPAWN_CHANSE = 20;
const int ENEMY_WITH_MOVEMENT_SPAWN_CHANSE = 30;
