#pragma once

const double CIRCLE_WEAK_ENEMY_SHAPE_SIZE = 35;
const double CIRCLE_STRONG_ENEMY_SHAPE_SIZE = 40;
const double CIRCLE_MIGHTY_ENEMY_SHAPE_SIZE = 45;

const double SQUARE_WEAK_ENEMY_SHAPE_SIZE = 28;
const double SQUARE_STRONG_ENEMY_SHAPE_SIZE = 33;
const double SQUARE_MIGHTY_ENEMY_SHAPE_SIZE = 38;

const sf::Color WEAK_ENEMY_SHAPE_COLOR = sf::Color::Red;
const sf::Color STRONG_ENEMY_SHAPE_COLOR = sf::Color::Green;
const sf::Color MIGHTY_ENEMY_SHAPE_COLOR = sf::Color::Cyan;

const double CIRCLE_WEAK_ENEMY_ATTACK_COOLDOWN = 700;
const double CIRCLE_STRONG_ENEMY_ATTACK_COOLDOWN = 850;
const double CIRCLE_MIGHTY_ENEMY_ATTACK_COOLDOWN = 1000;

const double SQUARE_WEAK_ENEMY_ATTACK_COOLDOWN = 900;
const double SQUARE_STRONG_ENEMY_ATTACK_COOLDOWN = 1050;
const double SQUARE_MIGHTY_ENEMY_ATTACK_COOLDOWN = 1200;

const int CIRCLE_WEAK_ENEMY_DAMAGE = 1;
const int CIRCLE_STRONG_ENEMY_DAMAGE = 2;
const int CIRCLE_MIGHTY_ENEMY_DAMAGE = 3;

const int SQUARE_WEAK_ENEMY_DAMAGE = 2;
const int SQUARE_STRONG_ENEMY_DAMAGE = 3;
const int SQUARE_MIGHTY_ENEMY_DAMAGE = 4;

const double WEAK_ENEMY_ATTACK_RANGE = 500;
const double STRONG_ENEMY_ATTACK_RANGE = 550;
const double MIGHTY_ENEMY_ATTACK_RANGE = 600;

const int WEAK_ENEMY_HEALTH = 5;
const int STRONG_ENEMY_HEALTH = 10;
const int MIGHTY_ENEMY_HEALTH = 15;

const double ENEMY_UNIT_SPEED = 0.15;

const int WEAK_ENEMY_ADDITIONAL_DAMAGE = 1;
const double STRONG_ENEMY_ADDITIONAL_ATTACK_RANGE_COEFFICIENT = 1.1;
const int MIGHTY_ENEMY_ADDITIONAL_HEALTH = 1;

const double CIRCLE_HERO_SHAPE_SIZE = 40;
const double SQUARE_HERO_SHAPE_SIZE = 30;
const sf::Color HERO_SHAPE_COLOR = sf::Color::White;
const double HERO_MOVE_SPEED = 0.6;
const double CIRCLE_HERO_ATTACK_COOLDOWN = 200;
const double SQUARE_HERO_ATTACK_COOLDOWN = 300;
const int CIRCLE_HERO_DAMAGE = 2;
const int SQUARE_HERO_DAMAGE = 3;
const double HERO_ATTACK_RANGE = 600;
const int HERO_HEALTH = 100;

const double BULLET_SPEED = 1.15;
const double BULLET_DEFLECTION_ANGLE = 0.3;

constexpr double ENEMY_SHAPE_MAX_SIZE = std::max({
CIRCLE_WEAK_ENEMY_SHAPE_SIZE,
CIRCLE_STRONG_ENEMY_SHAPE_SIZE,
CIRCLE_MIGHTY_ENEMY_SHAPE_SIZE,
SQUARE_WEAK_ENEMY_SHAPE_SIZE,
SQUARE_STRONG_ENEMY_SHAPE_SIZE,
SQUARE_MIGHTY_ENEMY_SHAPE_SIZE});
